package vista;

import vista.Carnes;
import vista.Bebidas;
import vista.Stars;
import vista.Vegetales;
import vista.Especiales;
import vista.Combo;


public class Home extends javax.swing.JFrame {

    
    public Home() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(logo, "src/imagenes/logo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(espeTXT, "src/imagenes/btnEspeciales.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(carneTXT, "src/imagenes/btnCarne.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(vegeTXT, "src/imagenes/btnVege.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(bebidasTXT, "src/imagenes/btnBebi.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(ComboTXT, "src/imagenes/btnCombo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(starsTXT, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnEXIT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnVegetales = new javax.swing.JPanel();
        vegeTXT = new javax.swing.JLabel();
        btnBebidas = new javax.swing.JPanel();
        bebidasTXT = new javax.swing.JLabel();
        btnCarnes = new javax.swing.JPanel();
        carneTXT = new javax.swing.JLabel();
        btnStars = new javax.swing.JPanel();
        starsTXT = new javax.swing.JLabel();
        btnCombos = new javax.swing.JPanel();
        ComboTXT = new javax.swing.JLabel();
        btnEspeciales = new javax.swing.JPanel();
        espeTXT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(786, 529));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        btnEXIT.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnEXIT.setForeground(new java.awt.Color(255, 255, 255));
        btnEXIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEXIT.setText("X");
        btnEXIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEXITMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 517, Short.MAX_VALUE)
                .addComponent(btnEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(-14, -20, 800, 160));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(241, 167, 18));

        btnVegetales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVegetales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        vegeTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vegeTXTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnVegetalesLayout = new javax.swing.GroupLayout(btnVegetales);
        btnVegetales.setLayout(btnVegetalesLayout);
        btnVegetalesLayout.setHorizontalGroup(
            btnVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
            .addGroup(btnVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vegeTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
        );
        btnVegetalesLayout.setVerticalGroup(
            btnVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(btnVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnVegetalesLayout.createSequentialGroup()
                    .addComponent(vegeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnBebidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBebidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bebidasTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidasTXTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnBebidasLayout = new javax.swing.GroupLayout(btnBebidas);
        btnBebidas.setLayout(btnBebidasLayout);
        btnBebidasLayout.setHorizontalGroup(
            btnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
            .addGroup(btnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnBebidasLayout.createSequentialGroup()
                    .addComponent(bebidasTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnBebidasLayout.setVerticalGroup(
            btnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
            .addGroup(btnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bebidasTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
        );

        btnCarnes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCarnes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        carneTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carneTXTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCarnesLayout = new javax.swing.GroupLayout(btnCarnes);
        btnCarnes.setLayout(btnCarnesLayout);
        btnCarnesLayout.setHorizontalGroup(
            btnCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carneTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        btnCarnesLayout.setVerticalGroup(
            btnCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carneTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnStars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnStars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        starsTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starsTXTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnStarsLayout = new javax.swing.GroupLayout(btnStars);
        btnStars.setLayout(btnStarsLayout);
        btnStarsLayout.setHorizontalGroup(
            btnStarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
            .addGroup(btnStarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(starsTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
        );
        btnStarsLayout.setVerticalGroup(
            btnStarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
            .addGroup(btnStarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(starsTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );

        btnCombos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCombos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ComboTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboTXTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCombosLayout = new javax.swing.GroupLayout(btnCombos);
        btnCombos.setLayout(btnCombosLayout);
        btnCombosLayout.setHorizontalGroup(
            btnCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCombosLayout.createSequentialGroup()
                .addComponent(ComboTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCombosLayout.setVerticalGroup(
            btnCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ComboTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        btnEspeciales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEspeciales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        espeTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espeTXTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnEspecialesLayout = new javax.swing.GroupLayout(btnEspeciales);
        btnEspeciales.setLayout(btnEspecialesLayout);
        btnEspecialesLayout.setHorizontalGroup(
            btnEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espeTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEspecialesLayout.setVerticalGroup(
            btnEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEspecialesLayout.createSequentialGroup()
                .addComponent(espeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("Hola. ¿Qué vas a pedir hoy?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCarnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEspeciales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVegetales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCarnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVegetales, javax.swing.GroupLayout.PREFERRED_SIZE, 206, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 780, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 529));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carneTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carneTXTMouseClicked
       Carnes carne = new Carnes();
       carne.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_carneTXTMouseClicked

    private void vegeTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegeTXTMouseClicked
        Vegetales vege = new Vegetales();
        vege.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vegeTXTMouseClicked

    private void bebidasTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidasTXTMouseClicked
        Bebidas bebi = new Bebidas();
        bebi = new Bebidas();
        this.dispose();
    }//GEN-LAST:event_bebidasTXTMouseClicked

    private void espeTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espeTXTMouseClicked
       Combo espe= new Combo();
       espe.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_espeTXTMouseClicked

    private void ComboTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboTXTMouseClicked
        Especiales combo = new Especiales();
        combo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComboTXTMouseClicked

    private void starsTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_starsTXTMouseClicked
        Stars etre = new Stars();
        etre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_starsTXTMouseClicked

    private void btnEXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEXITMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnEXITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComboTXT;
    private javax.swing.JLabel bebidasTXT;
    private javax.swing.JPanel btnBebidas;
    private javax.swing.JPanel btnCarnes;
    private javax.swing.JPanel btnCombos;
    private javax.swing.JLabel btnEXIT;
    private javax.swing.JPanel btnEspeciales;
    private javax.swing.JPanel btnStars;
    private javax.swing.JPanel btnVegetales;
    private javax.swing.JLabel carneTXT;
    private javax.swing.JLabel espeTXT;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel starsTXT;
    private javax.swing.JLabel vegeTXT;
    // End of variables declaration//GEN-END:variables
}
